package com.example.saa_project_db_engine.avro; /**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class HeapPageData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6402737992912589208L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"HeapPageData\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"previousPageId\",\"type\":\"int\"},{\"name\":\"nextPageId\",\"type\":\"int\"},{\"name\":\"records\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"TableRow\",\"fields\":[{\"name\":\"rowId\",\"type\":\"int\"},{\"name\":\"value\",\"type\":\"bytes\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<HeapPageData> ENCODER =
      new BinaryMessageEncoder<HeapPageData>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<HeapPageData> DECODER =
      new BinaryMessageDecoder<HeapPageData>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<HeapPageData> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<HeapPageData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<HeapPageData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<HeapPageData>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this HeapPageData to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a HeapPageData from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a HeapPageData instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static HeapPageData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int id;
  private int previousPageId;
  private int nextPageId;
  private java.util.List<TableRow> records;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public HeapPageData() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param previousPageId The new value for previousPageId
   * @param nextPageId The new value for nextPageId
   * @param records The new value for records
   */
  public HeapPageData(java.lang.Integer id, java.lang.Integer previousPageId, java.lang.Integer nextPageId, java.util.List<TableRow> records) {
    this.id = id;
    this.previousPageId = previousPageId;
    this.nextPageId = nextPageId;
    this.records = records;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return previousPageId;
    case 2: return nextPageId;
    case 3: return records;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: previousPageId = (java.lang.Integer)value$; break;
    case 2: nextPageId = (java.lang.Integer)value$; break;
    case 3: records = (java.util.List<TableRow>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public int getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(int value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'previousPageId' field.
   * @return The value of the 'previousPageId' field.
   */
  public int getPreviousPageId() {
    return previousPageId;
  }


  /**
   * Sets the value of the 'previousPageId' field.
   * @param value the value to set.
   */
  public void setPreviousPageId(int value) {
    this.previousPageId = value;
  }

  /**
   * Gets the value of the 'nextPageId' field.
   * @return The value of the 'nextPageId' field.
   */
  public int getNextPageId() {
    return nextPageId;
  }


  /**
   * Sets the value of the 'nextPageId' field.
   * @param value the value to set.
   */
  public void setNextPageId(int value) {
    this.nextPageId = value;
  }

  /**
   * Gets the value of the 'records' field.
   * @return The value of the 'records' field.
   */
  public java.util.List<TableRow> getRecords() {
    return records;
  }


  /**
   * Sets the value of the 'records' field.
   * @param value the value to set.
   */
  public void setRecords(java.util.List<TableRow> value) {
    this.records = value;
  }

  /**
   * Creates a new HeapPageData RecordBuilder.
   * @return A new HeapPageData RecordBuilder
   */
  public static HeapPageData.Builder newBuilder() {
    return new HeapPageData.Builder();
  }

  /**
   * Creates a new HeapPageData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new HeapPageData RecordBuilder
   */
  public static HeapPageData.Builder newBuilder(HeapPageData.Builder other) {
    if (other == null) {
      return new HeapPageData.Builder();
    } else {
      return new HeapPageData.Builder(other);
    }
  }

  /**
   * Creates a new HeapPageData RecordBuilder by copying an existing HeapPageData instance.
   * @param other The existing instance to copy.
   * @return A new HeapPageData RecordBuilder
   */
  public static HeapPageData.Builder newBuilder(HeapPageData other) {
    if (other == null) {
      return new HeapPageData.Builder();
    } else {
      return new HeapPageData.Builder(other);
    }
  }

  /**
   * RecordBuilder for HeapPageData instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<HeapPageData>
    implements org.apache.avro.data.RecordBuilder<HeapPageData> {

    private int id;
    private int previousPageId;
    private int nextPageId;
    private java.util.List<TableRow> records;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(HeapPageData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.previousPageId)) {
        this.previousPageId = data().deepCopy(fields()[1].schema(), other.previousPageId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.nextPageId)) {
        this.nextPageId = data().deepCopy(fields()[2].schema(), other.nextPageId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.records)) {
        this.records = data().deepCopy(fields()[3].schema(), other.records);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing HeapPageData instance
     * @param other The existing instance to copy.
     */
    private Builder(HeapPageData other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.previousPageId)) {
        this.previousPageId = data().deepCopy(fields()[1].schema(), other.previousPageId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.nextPageId)) {
        this.nextPageId = data().deepCopy(fields()[2].schema(), other.nextPageId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.records)) {
        this.records = data().deepCopy(fields()[3].schema(), other.records);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public int getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public HeapPageData.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public HeapPageData.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'previousPageId' field.
      * @return The value.
      */
    public int getPreviousPageId() {
      return previousPageId;
    }


    /**
      * Sets the value of the 'previousPageId' field.
      * @param value The value of 'previousPageId'.
      * @return This builder.
      */
    public HeapPageData.Builder setPreviousPageId(int value) {
      validate(fields()[1], value);
      this.previousPageId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'previousPageId' field has been set.
      * @return True if the 'previousPageId' field has been set, false otherwise.
      */
    public boolean hasPreviousPageId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'previousPageId' field.
      * @return This builder.
      */
    public HeapPageData.Builder clearPreviousPageId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'nextPageId' field.
      * @return The value.
      */
    public int getNextPageId() {
      return nextPageId;
    }


    /**
      * Sets the value of the 'nextPageId' field.
      * @param value The value of 'nextPageId'.
      * @return This builder.
      */
    public HeapPageData.Builder setNextPageId(int value) {
      validate(fields()[2], value);
      this.nextPageId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'nextPageId' field has been set.
      * @return True if the 'nextPageId' field has been set, false otherwise.
      */
    public boolean hasNextPageId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'nextPageId' field.
      * @return This builder.
      */
    public HeapPageData.Builder clearNextPageId() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'records' field.
      * @return The value.
      */
    public java.util.List<TableRow> getRecords() {
      return records;
    }


    /**
      * Sets the value of the 'records' field.
      * @param value The value of 'records'.
      * @return This builder.
      */
    public HeapPageData.Builder setRecords(java.util.List<TableRow> value) {
      validate(fields()[3], value);
      this.records = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'records' field has been set.
      * @return True if the 'records' field has been set, false otherwise.
      */
    public boolean hasRecords() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'records' field.
      * @return This builder.
      */
    public HeapPageData.Builder clearRecords() {
      records = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public HeapPageData build() {
      try {
        HeapPageData record = new HeapPageData();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.previousPageId = fieldSetFlags()[1] ? this.previousPageId : (java.lang.Integer) defaultValue(fields()[1]);
        record.nextPageId = fieldSetFlags()[2] ? this.nextPageId : (java.lang.Integer) defaultValue(fields()[2]);
        record.records = fieldSetFlags()[3] ? this.records : (java.util.List<TableRow>) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<HeapPageData>
    WRITER$ = (org.apache.avro.io.DatumWriter<HeapPageData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<HeapPageData>
    READER$ = (org.apache.avro.io.DatumReader<HeapPageData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.id);

    out.writeInt(this.previousPageId);

    out.writeInt(this.nextPageId);

    long size0 = this.records.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (TableRow e0: this.records) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readInt();

      this.previousPageId = in.readInt();

      this.nextPageId = in.readInt();

      long size0 = in.readArrayStart();
      java.util.List<TableRow> a0 = this.records;
      if (a0 == null) {
        a0 = new SpecificData.Array<TableRow>((int)size0, SCHEMA$.getField("records").schema());
        this.records = a0;
      } else a0.clear();
      SpecificData.Array<TableRow> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<TableRow>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          TableRow e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new TableRow();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readInt();
          break;

        case 1:
          this.previousPageId = in.readInt();
          break;

        case 2:
          this.nextPageId = in.readInt();
          break;

        case 3:
          long size0 = in.readArrayStart();
          java.util.List<TableRow> a0 = this.records;
          if (a0 == null) {
            a0 = new SpecificData.Array<TableRow>((int)size0, SCHEMA$.getField("records").schema());
            this.records = a0;
          } else a0.clear();
          SpecificData.Array<TableRow> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<TableRow>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              TableRow e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new TableRow();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










