package com.example.saa_project_db_engine.avro; /**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PageMetadata extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8884928035931265559L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PageMetadata\",\"fields\":[{\"name\":\"nextLogicalPageId\",\"type\":\"int\"},{\"name\":\"nextRowId\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PageMetadata> ENCODER =
      new BinaryMessageEncoder<PageMetadata>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PageMetadata> DECODER =
      new BinaryMessageDecoder<PageMetadata>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PageMetadata> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PageMetadata> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PageMetadata> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PageMetadata>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PageMetadata to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PageMetadata from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PageMetadata instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PageMetadata fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int nextLogicalPageId;
  private int nextRowId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PageMetadata() {}

  /**
   * All-args constructor.
   * @param nextLogicalPageId The new value for nextLogicalPageId
   * @param nextRowId The new value for nextRowId
   */
  public PageMetadata(java.lang.Integer nextLogicalPageId, java.lang.Integer nextRowId) {
    this.nextLogicalPageId = nextLogicalPageId;
    this.nextRowId = nextRowId;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return nextLogicalPageId;
    case 1: return nextRowId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: nextLogicalPageId = (java.lang.Integer)value$; break;
    case 1: nextRowId = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'nextLogicalPageId' field.
   * @return The value of the 'nextLogicalPageId' field.
   */
  public int getNextLogicalPageId() {
    return nextLogicalPageId;
  }


  /**
   * Sets the value of the 'nextLogicalPageId' field.
   * @param value the value to set.
   */
  public void setNextLogicalPageId(int value) {
    this.nextLogicalPageId = value;
  }

  /**
   * Gets the value of the 'nextRowId' field.
   * @return The value of the 'nextRowId' field.
   */
  public int getNextRowId() {
    return nextRowId;
  }


  /**
   * Sets the value of the 'nextRowId' field.
   * @param value the value to set.
   */
  public void setNextRowId(int value) {
    this.nextRowId = value;
  }

  /**
   * Creates a new PageMetadata RecordBuilder.
   * @return A new PageMetadata RecordBuilder
   */
  public static PageMetadata.Builder newBuilder() {
    return new PageMetadata.Builder();
  }

  /**
   * Creates a new PageMetadata RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PageMetadata RecordBuilder
   */
  public static PageMetadata.Builder newBuilder(PageMetadata.Builder other) {
    if (other == null) {
      return new PageMetadata.Builder();
    } else {
      return new PageMetadata.Builder(other);
    }
  }

  /**
   * Creates a new PageMetadata RecordBuilder by copying an existing PageMetadata instance.
   * @param other The existing instance to copy.
   * @return A new PageMetadata RecordBuilder
   */
  public static PageMetadata.Builder newBuilder(PageMetadata other) {
    if (other == null) {
      return new PageMetadata.Builder();
    } else {
      return new PageMetadata.Builder(other);
    }
  }

  /**
   * RecordBuilder for PageMetadata instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PageMetadata>
    implements org.apache.avro.data.RecordBuilder<PageMetadata> {

    private int nextLogicalPageId;
    private int nextRowId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(PageMetadata.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.nextLogicalPageId)) {
        this.nextLogicalPageId = data().deepCopy(fields()[0].schema(), other.nextLogicalPageId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.nextRowId)) {
        this.nextRowId = data().deepCopy(fields()[1].schema(), other.nextRowId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing PageMetadata instance
     * @param other The existing instance to copy.
     */
    private Builder(PageMetadata other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.nextLogicalPageId)) {
        this.nextLogicalPageId = data().deepCopy(fields()[0].schema(), other.nextLogicalPageId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.nextRowId)) {
        this.nextRowId = data().deepCopy(fields()[1].schema(), other.nextRowId);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'nextLogicalPageId' field.
      * @return The value.
      */
    public int getNextLogicalPageId() {
      return nextLogicalPageId;
    }


    /**
      * Sets the value of the 'nextLogicalPageId' field.
      * @param value The value of 'nextLogicalPageId'.
      * @return This builder.
      */
    public PageMetadata.Builder setNextLogicalPageId(int value) {
      validate(fields()[0], value);
      this.nextLogicalPageId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'nextLogicalPageId' field has been set.
      * @return True if the 'nextLogicalPageId' field has been set, false otherwise.
      */
    public boolean hasNextLogicalPageId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'nextLogicalPageId' field.
      * @return This builder.
      */
    public PageMetadata.Builder clearNextLogicalPageId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'nextRowId' field.
      * @return The value.
      */
    public int getNextRowId() {
      return nextRowId;
    }


    /**
      * Sets the value of the 'nextRowId' field.
      * @param value The value of 'nextRowId'.
      * @return This builder.
      */
    public PageMetadata.Builder setNextRowId(int value) {
      validate(fields()[1], value);
      this.nextRowId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'nextRowId' field has been set.
      * @return True if the 'nextRowId' field has been set, false otherwise.
      */
    public boolean hasNextRowId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'nextRowId' field.
      * @return This builder.
      */
    public PageMetadata.Builder clearNextRowId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PageMetadata build() {
      try {
        PageMetadata record = new PageMetadata();
        record.nextLogicalPageId = fieldSetFlags()[0] ? this.nextLogicalPageId : (java.lang.Integer) defaultValue(fields()[0]);
        record.nextRowId = fieldSetFlags()[1] ? this.nextRowId : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PageMetadata>
    WRITER$ = (org.apache.avro.io.DatumWriter<PageMetadata>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PageMetadata>
    READER$ = (org.apache.avro.io.DatumReader<PageMetadata>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.nextLogicalPageId);

    out.writeInt(this.nextRowId);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.nextLogicalPageId = in.readInt();

      this.nextRowId = in.readInt();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.nextLogicalPageId = in.readInt();
          break;

        case 1:
          this.nextRowId = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










