package com.example.saa_project_db_engine.avro; /**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class TableRow extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3924181759270406136L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TableRow\",\"fields\":[{\"name\":\"rowId\",\"type\":\"int\"},{\"name\":\"value\",\"type\":\"bytes\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TableRow> ENCODER =
      new BinaryMessageEncoder<TableRow>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TableRow> DECODER =
      new BinaryMessageDecoder<TableRow>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TableRow> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TableRow> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TableRow> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TableRow>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TableRow to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TableRow from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TableRow instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TableRow fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int rowId;
  private java.nio.ByteBuffer value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TableRow() {}

  /**
   * All-args constructor.
   * @param rowId The new value for rowId
   * @param value The new value for value
   */
  public TableRow(java.lang.Integer rowId, java.nio.ByteBuffer value) {
    this.rowId = rowId;
    this.value = value;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return rowId;
    case 1: return value;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: rowId = (java.lang.Integer)value$; break;
    case 1: value = (java.nio.ByteBuffer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'rowId' field.
   * @return The value of the 'rowId' field.
   */
  public int getRowId() {
    return rowId;
  }


  /**
   * Sets the value of the 'rowId' field.
   * @param value the value to set.
   */
  public void setRowId(int value) {
    this.rowId = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return The value of the 'value' field.
   */
  public java.nio.ByteBuffer getValue() {
    return value;
  }


  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.nio.ByteBuffer value) {
    this.value = value;
  }

  /**
   * Creates a new TableRow RecordBuilder.
   * @return A new TableRow RecordBuilder
   */
  public static TableRow.Builder newBuilder() {
    return new TableRow.Builder();
  }

  /**
   * Creates a new TableRow RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TableRow RecordBuilder
   */
  public static TableRow.Builder newBuilder(TableRow.Builder other) {
    if (other == null) {
      return new TableRow.Builder();
    } else {
      return new TableRow.Builder(other);
    }
  }

  /**
   * Creates a new TableRow RecordBuilder by copying an existing TableRow instance.
   * @param other The existing instance to copy.
   * @return A new TableRow RecordBuilder
   */
  public static TableRow.Builder newBuilder(TableRow other) {
    if (other == null) {
      return new TableRow.Builder();
    } else {
      return new TableRow.Builder(other);
    }
  }

  /**
   * RecordBuilder for TableRow instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TableRow>
    implements org.apache.avro.data.RecordBuilder<TableRow> {

    private int rowId;
    private java.nio.ByteBuffer value;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(TableRow.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.rowId)) {
        this.rowId = data().deepCopy(fields()[0].schema(), other.rowId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing TableRow instance
     * @param other The existing instance to copy.
     */
    private Builder(TableRow other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.rowId)) {
        this.rowId = data().deepCopy(fields()[0].schema(), other.rowId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'rowId' field.
      * @return The value.
      */
    public int getRowId() {
      return rowId;
    }


    /**
      * Sets the value of the 'rowId' field.
      * @param value The value of 'rowId'.
      * @return This builder.
      */
    public TableRow.Builder setRowId(int value) {
      validate(fields()[0], value);
      this.rowId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'rowId' field has been set.
      * @return True if the 'rowId' field has been set, false otherwise.
      */
    public boolean hasRowId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'rowId' field.
      * @return This builder.
      */
    public TableRow.Builder clearRowId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getValue() {
      return value;
    }


    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public TableRow.Builder setValue(java.nio.ByteBuffer value) {
      validate(fields()[1], value);
      this.value = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public TableRow.Builder clearValue() {
      value = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TableRow build() {
      try {
        TableRow record = new TableRow();
        record.rowId = fieldSetFlags()[0] ? this.rowId : (java.lang.Integer) defaultValue(fields()[0]);
        record.value = fieldSetFlags()[1] ? this.value : (java.nio.ByteBuffer) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TableRow>
    WRITER$ = (org.apache.avro.io.DatumWriter<TableRow>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TableRow>
    READER$ = (org.apache.avro.io.DatumReader<TableRow>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.rowId);

    out.writeBytes(this.value);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.rowId = in.readInt();

      this.value = in.readBytes(this.value);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.rowId = in.readInt();
          break;

        case 1:
          this.value = in.readBytes(this.value);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










